### PR TITLE
Lower MAX_WRITE to 64KB

### PR DESCRIPTION
**Pull request by mcollina**
This seems a good idea to do given how the current mechanism work in v2.

### CODE REVIEW

**Review by ronag — APPROVED** [review]

**Comment by mcollina** [comment]
@ronag could you verify if it fixes your problems?

**Comment by ronag** [comment]
> @ronag could you verify if it fixes your problems?

Little difficult. Takes a lot of effort so I'd like to understand why you think this would help?

**Comment by mcollina** [comment]
A comment in the other issue showed a truncation really close to 64KB. Therefore there might be some bad interaction there. It also seems a safer number.

**Comment by ronag** [comment]
It's easier if you make a release. Any reason to not do this?

**Comment by ronag** [comment]
Deployed to production. I'll keep you posted.

**Comment by ronag** [comment]
Still a problem.

**Comment by ronag** [comment]
```js
"{\"level\":10,\"time\":1642499089410,\"pid\":1,\"hostname\":\"930e931ebfd6\",\"name\":\"search\",\"id\":8255,\"type\":\"conditional\",\"query\":{\"type\":\"conditional\",\"roles\":[\"MTuN0064_LMily\",\"administrator\"],\"searches\":[\"MbQLOxd3Y75THC\"],\"query\":\"_id:\\\"gallery4\\\"\",\"hidden\":null,\"count\":1,\"refreshInterval\":1000},\"refreshInterval\":1000,\"msg\":\"Refreshing search\"{\"level\":10,\"time\":1642499089410,\"pid\":1,\"hostname\":\"930e931ebfd6\",\"name\":\"search\",\"id\":8258,\"type\":\"conditional\",\"query\":{\"type\":\"conditional\",\"roles\":null,\"searches\":[\"ScwjUlMmbQePRm\"],\"query\":\"_id:\\\"NGaS6Ma1uS7KTD\\\"\",\"count\":1,\"refreshInterval\":1000},\"refreshInterval\":1000,\"msg\":\"Refreshing search\"}"
```

**Comment by mcollina** [comment]
I really need a repro.

**Comment by ronag** [comment]
Yea, I get that. We are trying.

**Comment by ronag** [comment]
@mcollina Could we make some kind of debug version which could provide us with more info? I don't know exactly what that would mean in practice though. I think we can run a low perf version of sonic-boom in production.

**Pull request merged**
