### PR TITLE
Fix TS types

### LINKED ISSUE #74: types are outdated
example:

- https://github.com/pinojs/sonic-boom/blob/master/index.js#L85
- https://github.com/pinojs/sonic-boom/blob/master/types/index.d.ts#L16

Not sure why the tests, pass. Are they run in CI?

### PR DESCRIPTION
**Pull request by kibertoad**
Update typings to reflect current version of sonic-boom
fixes #74

### CODE REVIEW

**Comment by kibertoad** [comment]
@kilianc Could you please review?

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by kibertoad** [comment]
@mcollina Any chance you could publish a new version?

**Comment by mcollina** [comment]
Should be shipped!

**Pull request merged**
