### PR TITLE
prevent memory leak when writing before ready

### PR DESCRIPTION
**Pull request by rluvaton**
while trying to add a callback function to flush in `pino` I got into a situation where I logged and flushed before the file was ready so the cb never got called

### CODE REVIEW

**Comment by rluvaton** [comment]
I just noticed that the branch name has nothing to do with the fix 😅

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by rluvaton** [comment]
let's merge this so I can continue working on pino flush? (don't forget hacktoberfest 😅  I need some shirts 😂 )

**Comment by rluvaton** [comment]
Can you please release that so pinojs/pino#1827 can be merged?

**Pull request merged**
